### ISSUE TITLE
[BUG]生成的文档的锚点功能好像不能用

### ISSUE THREAD

**Issue by Lohoyo** [kidnes/san-docit#1]
比如，我点击下图所示的地方后获取到的URL，再次打开后没有锚点到对应的位置。

![image](https://user-images.githubusercontent.com/28821810/109159620-cac7b580-77af-11eb-9df6-464eb602bd09.png)

你也可以试试：https://ecomfe.github.io/san-cli/create-project/

**Comment by kidnes** [comment]
1.0.4版本已解决
